### ISSUE TITLE
Verify the bot so it can be added to more servers

### ISSUE THREAD

**Issue by EddieEldridge** [dhrumilp15/haystackfs#74]
![image](https://user-images.githubusercontent.com/22448079/144640109-79f698ab-5c40-4635-90fa-f816c0cf1be8.png)

**Comment by dhrumilp15** [comment]
Oh yeah - we have been in the process of verification for a little bit. I'll send a follow-up

**Comment by dhrumilp15** [comment]
We're now verified!
