### ISSUE TITLE
Custom type file search not working properly

### ISSUE THREAD

**Issue by pelasO** [dhrumilp15/haystackfs#89]
It does work with almost all file extensions I have tried but there's a kind of it, .STO files.
No matter how you set the bot, it will give you no results; it's like if the bot goes into a loop.

![IMG_8819](https://user-images.githubusercontent.com/3640620/154799216-72a4259a-53ce-41fd-b07c-470e63fee088.jpeg)

Attached the type of file I'm using

**Comment by pelasO** [comment]
https://discord.com/channels/812818660141170748/864397422846017536/943849907796725790

**Comment by dhrumilp15** [comment]
Resolved! This should be functioning in the current iteration of the bot!
